#!/usr/bin/env bash
set -euo pipefail

read -r -a args <<< "$1"

command=${args[0]}
mac=${args[1]}

[[ "${command}" =~ ^[a-zA-Z]*$ ]] || die "Invalid command"

[[ "${mac}" =~ ^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$ ]] || die "Invalid mac address"

bluetoothctl "${command}" "${mac}"