#!/usr/bin/env bash
set -euo pipefail

read -r -a args <<< "$1"

sink=${args[0]}
volume=${args[1]}

min_volume=0
max_volume=100

volume=$(( volume < max_volume ? volume : max_volume ))
volume=$(( volume > min_volume ? volume : min_volume ))

pactl set-sink-volume "${sink}" "${volume}%"